### ISSUE TITLE
Адаптация проекта

### ISSUE THREAD

**Issue by promavto** [Porokhnya/GreenhouseProject#1]
Ваш проект очень хорошо выполнен!
Надеюсь применить в своей версии. управления теплицей.
Проблема в том, что мой контроллер уже изготовлен.
Надеюсь адаптировать Ваши программы к моей аппаратной части.
Изучаю Ваш вариант.
Прошу сообщить есть ли возможность получить исходники на SOFT (GreenHouseConfig.exe, LogViewer.exe).

С Уважением!
Александр.
 Зеленоград, Москва.
promavto@ntmp.ru
https://github.com/Teplitca

**Comment by Porokhnya** [comment]
Здравствуйте, Александр!

Исходники софта в свободный доступ я выкладывать не планирую.

13 апреля 2016 г., 12:26 пользователь promavto <notifications@github.com>
написал:

**Comment by promavto** [comment]
Согласен!

Благодарю за быстрый ответ.

Работа Вами проделана большая, особенно подготовка документации.
Предложить взамен что то  специалисту Вашего уровня ничего равноценного не смогу. (может разработку печатной платы на контроллер).  А не в свободный доступ, персонально мне?  Я , правда, в основном программирую на С#.
Но на все нужно время. В моем возрасте стараюсь его экономить ;-).  Не хочется изобретать велосипед, а хорошо выполненных работ в интернете очень мало.
Я большой любитель садоводства, но заботу о растениях выполняет супруга. Хочу немного автоматизировать ее труд.
Для справки: в моем контроллере кроме стандартных датчиков всевозможных датчиков измерения параметров воздуха, применяется 7" дисплей, механическое открывание окон. В качестве определения положения окна применяются электронные компасы, распределительный полив 16 клапанами, WiFi итд. 


С уважением!
Александр.

 





  ----- Original Message -----

**Comment by Porokhnya** [comment]
Александр, не знаю, чем вам смогут помочь исходники конфигуратора, учитывая тот факт, что исходники прошивки полностью открыты, протокол в основном описан, и вы, используя стандартный компонент SerialPort - можете написать софт так, как нужно именно вам. Особенно учитывая тот факт, что у вас другая железная периферия.

Насчёт предложения по разработке печатной платы - спасибо, но сейчас это делать несколько преждевременно, поскольку проект ещё в стадии разработки, и уровень готовности программной части, по осторожным и оптимистичным прикидкам, составляет около 50%.

Резюмируя: учитывая вышеизложенное, вынужден огорчить вас и ещё раз упомянуть, что я не планирую выкладывать исходники конфигуратора и просмотрщика лог-файлов в свободный доступ. 

Спасибо за ваш интерес к проекту.

**Comment by promavto** [comment]
Ок!


  ----- Original Message -----
