### ISSUE TITLE
Структуризация, компиляция, управление

### ISSUE THREAD

**Issue by livello** [Porokhnya/GreenhouseProject#3]
Бегло просмотрел проект:
1) бросается в глаза отсутствие вменяемого дерева каталогов. Все в одной куче по принципу - авось пригодится, пусть будет под рукой. У новичка разбегаются глаза и ничего не понятно с ходу.

2) скомпилировать проект можно только в Ардуино ИДЕ? Почему бы не сделать поддержку plarformio? Надо всего лишь добавить один конфигурационный файл. Зато как здорово бы собирался проект:
git clone ....
pio run --target upload
И все.
Такая поддержка позволила бы использоать Clion - мощнейшую IDE для плюсов.

3) ручное управление в консольном режиме - основное? Почему-то на нём сделан акцент, а остальные режимы куда-то затерялись.

**Comment by Porokhnya** [comment]
1. В одной удобной куче, мне больше не надо. Новичку в проект и так войти сложно, чем поможет дерево каталогов - неясно;

2. Можно компилировать и в Visual Studio, поставьте Visual Micro и будет счастье. Под другими платформами - не пробовал, неинтересно;

3. В смысле "ручное управление в консольном режиме"? Есть конфигуратор, GUI-интерфейс. Есть веб-интерфейс. Можно по MQTT через любой GUI-MQTT-клиент управлять. Если хочется - можно и ручками через puTTY, например - не вопрос. Никто акцента на ручном управлении не делал: настроенный контроллер делает всю работу автоматически, незачем туда постоянно тыкаться для управления.
