### ISSUE TITLE
Usage of the Arduino Wire library.

### ISSUE THREAD

**Issue by Koepel** [Porokhnya/GreenhouseProject#4]
Hi, I noticed a few things in the usage of the Wire libray.
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes)

- GreenhouseProject/UniversalSensorsModule/BH1750.cpp 
   beginTransmission() and endTransmission() with Wire.requestFrom().
-  GreenhouseProject/Main/HTU21D.cpp  
   waiting and endTransmission() after Wire.requestFrom().
-  GreenhouseProject/UniversalSensorsModule/HTU21D.cpp
   waiting and endTransmission() after Wire.requestFrom().
-  GreenhouseProject/Main/LuminosityModule.cpp
   beginTransmission() and endTransmission() with Wire.requestFrom().
-  GreenhouseProject/Main/PHModule.cpp 
   beginTransmission() and endTransmission() with Wire.requestFrom().

**Comment by Porokhnya** [comment]
Thanks for feedback, but i think that it is not so serious mistakes, but I'll try to fix it in next updates.

**Comment by Koepel** [comment]
That's okay. At this moment they are not serious. However, using a Wire.endTransmssion() after a Wire.requestFrom() could have unpredictable results with other implementations of the Wire library and perhaps in the future.
